# Generated by Django 5.1 on 2024-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "role",
                    models.CharField(
                        choices=[("trainer", "Trainer"), ("lead", "Lead")],
                        help_text="Role of the member.",
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the member.",
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the member.", max_length=100
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when a member was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when a member was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Members",
                "ordering": ["full_name"],
            },
        ),
    ]
