# Generated by Django 5.1 on 2024-09-02 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for the tasks.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the task.", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unclaimed", "Unclaimed"),
                            ("in_progress", "In Progress"),
                            ("in_review", "In Review"),
                            ("completed", "Completed"),
                        ],
                        help_text="Current status of the task.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when a member was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when a member was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tasks",
                "ordering": ["name"],
            },
        ),
    ]
